<?php

namespace Database\Seeders;

use App\Models\Informasi;
use Illuminate\Database\Seeder;

class InformasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Informasi::create([
            'judul' => 'Informasi 1',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum. <br /> ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum',
            'gambar' => 'info.jpg',
        ]);

        Informasi::create([
            'judul' => 'Informasi 2',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat.',
            'gambar' => 'info.jpg',
        ]);

        Informasi::create([
            'judul' => 'Informasi 3',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat.',
            'gambar' => 'info.jpg',
        ]);

        Informasi::create([
            'judul' => 'Informasi 4',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat.',
            'gambar' => 'info.jpg',
        ]);

        Informasi::create([
            'judul' => 'Informasi 5',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat.',
            'gambar' => 'info.jpg',
        ]);

        Informasi::create([
            'judul' => 'Informasi 6',
            'user_id' => 1,
            'isi' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. <br /> Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat. Sed euismod, ipsum eget sagittis porttitor, nisi nunc egestas nisi, eu tincidunt nunc nisi euismod erat.',
            'gambar' => 'info.jpg',
        ]);
    }
}
